version: '3.8'

services:
  osart-api:
    build:
      context: ./osart-api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./osart-api/.env
    restart: always

  osart-store:
    build:
      context: ./osart-store
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./osart-store/.env.local
    depends_on:
      - osart-api
    restart: always
