services:
  osart-api:
    build:
      context: ./osart-api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./osart-api/.env
    healthcheck:
      test: [ "CMD", "wget", "-no-verbose", "--tries=1", "--spider", "http://localhost:3001/graphql" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  osart-store:
    build:
      context: ./osart-store
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./osart-store/.env.local
    depends_on:
      osart-api:
        condition: service_healthy
    restart: always
